name: Build Heat-PINN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Get uv
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install uv
  
      - name: uv sync
        shell: bash
        run: uv sync
      
      - name: uv build
        shell: bash
        run: uv build && ls -l
      
      - name: uv tool
        shell: bash
        run: |
          uv tool install .
      
      - name: check model builder
        shell: bash
        run: |
          heat build --help

      - name: check model trainer
        shell: bash
        run: |
          heat train --help
  
      - name: check model inference
        shell: bash
        run: |
          heat infer --help