name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Build wheel
        run: |
          uv build
          ls -lah dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
          if-no-files-found: error
          retention-days: 1

  make_geometry:
    name: Make Geometry
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: pip install --upgrade pip && pip install -r requirements.txt
      
      - name:  Make geometry data
        shell: bash
        run: |
            mkdir -p data/square
            python3 utils/square.py \
            --data-per-boundary 25 \
            --Nc 10000 \
            --output-path data/square \
            --bc-values 0 0.5 0.3 1
            tree
      
      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: datasets
          path: data/square/*.parquet
          if-no-files-found: error
          retention-days: 1
  
  test:
    name: Test
    needs: 
      - build
      - make_geometry
    
    runs-on: ubuntu-22.04
   
    permissions:
      contents: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: datasets
          path: data/square
      
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - name: Inspect artifact
        run: ls -lah dist

      - name: Build model
        run: |
          uv tool run --from dist/*.whl heat build \
            --in-shape 2 \
            --out-shape 1 \
            --n-hidden-layers 1 \
            --neuron-per-layer 10 \
            --actfun tanh \
            --name test_model.joblib
      
      - name: Train model
        run: |
          uv tool run --from dist/*.whl heat train \
            --domain data/square/domain_data.parquet \
            --boundary data/square/boundary_data.parquet \
            --model test_model.joblib \
            --epochs 1000 \
            --every 100
    
      - name: Inference
        run: |
          uv tool run --from dist/*.whl heat infer \
            --data data/square/domain_data.parquet \
            --model test_model.joblib \
            --output data/inference.parquet

      - name: Generate plot
        run: |
          python3 scripts/plot_2d.py data/inference.parquet assets/${{ github.run_id }}.png

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update asset files"
          branch: "update-assets"
          delete-branch: true
          title: "Adding new assets in validation workflow"
          body: "This PR was automatically generated by the Validation workflow."
          labels: "automated-pr"
